ref:
  # bwa index
  hindex: "hg38"
  # gtf index
  sannotation: "/opt/data/example_data/example_data/references/GCF_009858895.2_ASM985889v3_genomic.gff"
  # Host Reference
  #hreference: "references/GCF_000001405.38_GRCh38.p12_genomic.fna.gz"
  # Species Reference
  sreference: "/opt/data/example_data/references/GCF_009858895.2_ASM985889v3_genomic.fna"
  # sreference index
  srefindex:  "/opt/data/example_data/seqindex/covid"
  # primer fasta
  primerfa: "/opt/data/example_data/references/pri_adaptors.fa"
parameters:
  # qscore min value
  qvalue: "30"
  # insert size estimated
  insertsize: "300"
  # logstr
  logstr: "TrimLog"
  # kmerbest
  kmerbest: "27"
  # primer_adaptor fasta
  pri_adaptors: "/opt/data/example_data/references/pri_adaptors.fa"
dir_paths:
    # base_dir path
    base_dir: "/opt/data/"
    # reference dir_paths
    ref_dir_path: "/opt/data/example_data/seqindex/makona"
    # work_dir
    work_dir: "/opt/data/example_data"
    #result_dir
    result_dir: "/opt/data/example_data/results"
