ref:
  # bwa index
  hindex: "hg38"
  # gtf index
  sannotation: "/home/guest/projects/makona/references/GCF_009858895.2_ASM985889v3_genomic.gff"
  # Host Reference
  #hreference: "references/GCF_000001405.38_GRCh38.p12_genomic.fna.gz"
  # Species Reference
  sreference: "/home/guest/projects/makona/references/GCF_009858895.2_ASM985889v3_genomic.fna"
  # sreference index
  srefindex:  "/home/guest/projects/makona/seqindex/covid"
  # primer fasta
  primerfa: "references/pri_adaptors.fa"
parameters:
  # qscore min value
  qvalue: "30"
  # insert size estimated
  insertsize: "300"
  # logstr
  logstr: "TrimLog"
  # kmerbest
  kmerbest: "27"
  # primer_adaptor fasta
  pri_adaptors: "/home/guest/projects/makona/references/pri_adaptors.fa"
dir_paths:
    # base_dir path
    base_dir: "/home/guest/projects/"
    # reference dir_paths
    ref_dir_path: "/seqindex/makona"
    # tool path
    tool_path: "/home/guest/projects/tools/"
    # work_dir
    work_dir: "/makona"
    #result_dir
    result_dir: "/makona/results"
